[project]
name = "rust-resnet50-inference"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "onnx>=1.19.0",
    "onnxruntime>=1.22.1",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]
